---
# cPanel deployment configuration for Astro
# Documentación: https://docs.cpanel.net/knowledge-base/web-services/how-to-set-up-git-version-control/

deployment:
  tasks:
    - export NODE_ENV=production
    - npm install --legacy-peer-deps
    - npm run build
    - rsync -a --delete dist/ ~/homex/fundacio/
