# Netlify configuration for Fundación DAADIOS

[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Form handling
[[plugins]]
  package = "@netlify/plugin-forms"

# Redirects
[[redirects]]
  from = "/aplicar-beca"
  to = "/#aplicar"
  status = 301

[[redirects]]
  from = "/contacto"
  to = "/#contacto"
  status = 301
